# Generated by Django 5.0.3 on 2024-03-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.IntegerField(verbose_name='Номер версии')),
                ('name_version', models.CharField(max_length=150, verbose_name='Название версии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Признак')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketApp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
