# Generated by Django 5.0.3 on 2024-04-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0006_alter_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
